name: build-and-publish

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    name: release
    steps: 
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.YOUTD2_PAT_TOKEN }}

    - name: install and build
      run: | 
        npm install
        npm run build
        sentry:sourcemaps
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}


    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
        cname: youtd2.com
